version: '3.9'
services:
    database:
      image: mongo
      restart: always
      ports:
        - 27017:27017
      networks:
        - benzine
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: rootpwd
networks:
  benzine: