openapi: 3.0.0
info:
  title: Benzine api
  description: This api serves the benzine app.
  version: 1.0.0

servers:
  - url: https://bezine-api.janvanoverbeek.nl/

paths:
  /user/{id}:
    $ref: ./user/getUser.yaml
  /user/login:
    $ref: ./user/login.yaml
  /user/register:
    $ref: ./user/register.yaml