name: "Docker Image Releases"
on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04

    steps:
      -
        name: Install jq
        run: sudo apt install jq -y
      -
        name: Get tags
        run: curl https://api.github.com/repos/jannyboy313/benzine-verbruik/tags > tags.json
      -
        name: save latest tag
        id: vars
        run: echo "TAG_VERSION=$(jq -r '.[0].name' tags.json)" >> $GITHUB_OUTPUT
      -
        name: Outputting tag
        run: echo ${{ steps.vars.TAG_VERSION }}
      -
        name: Checkout repo
        uses: actions/checkout@main
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push tagged web image
        uses: docker/build-push-action@v3
        with:
          context: ./web
          file: Dockerfile.webProd
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/web-benzine-verbruik:latest,${{ secrets.DOCKER_HUB_USERNAME }}/web-benzine-verbruik:${{ steps.vars.tagversion }}
      -
        name: Build and push tagged api image
        uses: docker/build-push-action@v3
        with:
          context: ./api
          file: Dockerfile.apiProd
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/api-benzine-verbruik:latest,${{ secrets.DOCKER_HUB_USERNAME }}/api-benzine-verbruik:${{ steps.vars.tagversion }}
