name: "Docker Image Releases"
on:
  release:
    types: [ published ]
  workflow_dispatch:
env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  IMAGE_TAG: ${{ github.event.release.tag_name }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04

    steps:
      -
        name: Install jq
        run: sudo apt install jq -y
      -
        name: Get latest tag
        id: vars
        run: echo "tagversion=$(curl -sL https://api.github.com/repos/jannyboy313/benzine-verbruik/tags |jq -r '.[0].name')" >> $GITHUB_OUTPUT
      -
        name: Output latest tag
        run: echo ${{steps.vars.output.tagversion}}
      -
        name: Checkout repo
        uses: actions/checkout@main
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push tagged web image
        uses: docker/build-push-action@v3
        with:
          context: ./web
          file: Dockerfile.webProd
          push: true
          tags: ${{ env.USERNAME }}/web-benzine-verbruik:latest,${{ env.USERNAME }}/web-benzine-verbruik:${{ env.IMAGE_TAG }}
          build-args: |
            USERNAME=${{ secrets.DOCKER_HUB_USERNAME }}
            IMAGE_TAG=${{ github.event.release.tag_name }}
      -
        name: Build and push tagged api image
        uses: docker/build-push-action@v3
        with:
          context: ./api
          file: Dockerfile.apiProd
          push: true
          tags: ${{ env.USERNAME }}/api-benzine-verbruik:latest,${{ env.USERNAME }}/api-benzine-verbruik:${{ env.IMAGE_TAG }}
          build-args: |
            USERNAME=${{ secrets.DOCKER_HUB_USERNAME }}
            IMAGE_TAG=${{ github.event.release.tag_name }}
