name: "Docker Image Releases"
on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04

    steps:
      -
        name: Checkout repo
        uses: actions/checkout@main
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Get the version
        id: vars
        run: echo "{tag}={$GITHUB_REF:10}" >> $GITHUB_OUTPUT
      -
        name: Build and push tagged web image
        uses: docker/build-push-action@v3
        with:
          context: ./web
          file: Dockerfile.webProd
          push: true
          tags: jannyboy313/web-benzine-verbruik:latest,jannyboy313/web-benzine-verbruik:${{steps.vars.output.tag}}
      -
        name: Build and push tagged api image
        uses: docker/build-push-action@v3
        with:
          context: ./api
          file: Dockerfile.apiProd
          push: true
          tags: jannyboy313/api-benzine-verbruik:latest,jannyboy313/api-benzine-verbruik:${{steps.vars.output.tag}}