name: Format checking
on:
  pull_request:
    branches:
      - development


jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          dry: True
          prettier_options: --config ./.prettierrc --check {,!(node_modules)/**/}*.{js,ts,html,yaml,scss}
