name: Formatting
on:
  push:
    branches:
      - development


jobs:
  prettier:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          prettier_options: --config ./.prettierrc --write {,!(node_modules)/**/}*.{js,ts,html,yaml,scss}
